apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: loki-monitor
  labels:
    monitor: 'true'
spec:
  selector:
    matchLabels:
      app: loki
  podMetricsEndpoints:
    - interval: 15s
      scrapeTimeout: 10s
      port: http-metrics