apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [analytics]
    reporting_enabled = false
    [auth.anonymous]
    enabled = true
    org_role = Admin
    [explore]
    enabled = true
    [server]
    http_port = 3000
    [users]
    default_theme = dark