apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  loki.yml: |
    apiVersion: 1
    datasources:
      - access: proxy
        basicAuth: false
        basicAuthPassword: ""
        basicAuthUser: ""
        editable: false
        isDefault: false
        name: loki
        type: loki
        url: http://loki:3100
        version: 3
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - access: proxy
        editable: false
        isDefault: true
        jsonData:
            httpMethod: GET
        name: prometheus
        type: prometheus
        url: http://prometheus:9090
        version: 1